### ISSUE TITLE
Possible to add total games played column?

### ISSUE THREAD

**Issue by cohancarpentier** [thekogmo/race-to-masters#1]

**Comment by thekogmo** [comment]
It would be nice to have! I currently show a column for the number of wins and losses, so some people might say it would be a bit redundant (people can do the math in their head if they want). If I had to choose between "total games" and "win ratio" i think win ratio is more useful for the current challenge. And that W/L column itself is hidden on smaller screens with less real estate. I only have 400pixels width to work with on mobile.

I had many ideas for columns, like the current win streak and so on. But I have to always worry about mobile screens. Maybe for future iterations I can change the mobile version layout to something a bit better than a table. like maybe stack the cells vertically? but it's a trade-off with simplicity, especially when there are more participants, the current layout on mobile is great for a large number of participants.

But overall I agree, it would be nice to have. I'll consider this when designing the next version 👍
